[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.10.0"
  NEXT_USE_NETLIFY_EDGE = "true"

[[redirects]]
  from = "/*"
  to = "/_netlify_handler"
  status = 200

[images]
  remote_images = [
    "https://ext.same-assets.com/.*",
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ugc.same-assets.com/.*"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"
